//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationChurnConfig) DeepCopyInto(out *AnnotationChurnConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationChurnConfig.
func (in *AnnotationChurnConfig) DeepCopy() *AnnotationChurnConfig {
	if in == nil {
		return nil
	}
	out := new(AnnotationChurnConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupConfig) DeepCopyInto(out *CleanupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupConfig.
func (in *CleanupConfig) DeepCopy() *CleanupConfig {
	if in == nil {
		return nil
	}
	out := new(CleanupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTypeConfig) DeepCopyInto(out *EventTypeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTypeConfig.
func (in *EventTypeConfig) DeepCopy() *EventTypeConfig {
	if in == nil {
		return nil
	}
	out := new(EventTypeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsConfig) DeepCopyInto(out *EventsConfig) {
	*out = *in
	if in.EventTypes != nil {
		in, out := &in.EventTypes, &out.EventTypes
		*out = make([]EventTypeConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsConfig.
func (in *EventsConfig) DeepCopy() *EventsConfig {
	if in == nil {
		return nil
	}
	out := new(EventsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadGenerationMetrics) DeepCopyInto(out *LoadGenerationMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadGenerationMetrics.
func (in *LoadGenerationMetrics) DeepCopy() *LoadGenerationMetrics {
	if in == nil {
		return nil
	}
	out := new(LoadGenerationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadProfile) DeepCopyInto(out *LoadProfile) {
	*out = *in
	if in.NamespacesPerNode != nil {
		in, out := &in.NamespacesPerNode, &out.NamespacesPerNode
		*out = new(string)
		**out = **in
	}
	if in.ResourcesPerNamespace != nil {
		in, out := &in.ResourcesPerNamespace, &out.ResourcesPerNamespace
		*out = new(int32)
		**out = **in
	}
	if in.APICallRate != nil {
		in, out := &in.APICallRate, &out.APICallRate
		*out = new(int32)
		**out = **in
	}
	if in.APICallRateStatic != nil {
		in, out := &in.APICallRateStatic, &out.APICallRateStatic
		*out = new(int32)
		**out = **in
	}
	if in.APICallRatePerNode != nil {
		in, out := &in.APICallRatePerNode, &out.APICallRatePerNode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadProfile.
func (in *LoadProfile) DeepCopy() *LoadProfile {
	if in == nil {
		return nil
	}
	out := new(LoadProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceConfig) DeepCopyInto(out *NamespaceConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = new(NamespaceResourceQuota)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceConfig.
func (in *NamespaceConfig) DeepCopy() *NamespaceConfig {
	if in == nil {
		return nil
	}
	out := new(NamespaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceResourceQuota) DeepCopyInto(out *NamespaceResourceQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceResourceQuota.
func (in *NamespaceResourceQuota) DeepCopy() *NamespaceResourceQuota {
	if in == nil {
		return nil
	}
	out := new(NamespaceResourceQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceChurnConfig) DeepCopyInto(out *ResourceChurnConfig) {
	*out = *in
	out.ConfigMaps = in.ConfigMaps
	out.Secrets = in.Secrets
	out.Routes = in.Routes
	out.ImageStreams = in.ImageStreams
	out.BuildConfigs = in.BuildConfigs
	in.Events.DeepCopyInto(&out.Events)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceChurnConfig.
func (in *ResourceChurnConfig) DeepCopy() *ResourceChurnConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceChurnConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceCounts) DeepCopyInto(out *ResourceCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceCounts.
func (in *ResourceCounts) DeepCopy() *ResourceCounts {
	if in == nil {
		return nil
	}
	out := new(ResourceCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTypeConfig) DeepCopyInto(out *ResourceTypeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTypeConfig.
func (in *ResourceTypeConfig) DeepCopy() *ResourceTypeConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceTypeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleLoadConfig) DeepCopyInto(out *ScaleLoadConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleLoadConfig.
func (in *ScaleLoadConfig) DeepCopy() *ScaleLoadConfig {
	if in == nil {
		return nil
	}
	out := new(ScaleLoadConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScaleLoadConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleLoadConfigList) DeepCopyInto(out *ScaleLoadConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScaleLoadConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleLoadConfigList.
func (in *ScaleLoadConfigList) DeepCopy() *ScaleLoadConfigList {
	if in == nil {
		return nil
	}
	out := new(ScaleLoadConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScaleLoadConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleLoadConfigSpec) DeepCopyInto(out *ScaleLoadConfigSpec) {
	*out = *in
	if in.KwokNodeSelector != nil {
		in, out := &in.KwokNodeSelector, &out.KwokNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.LoadProfile.DeepCopyInto(&out.LoadProfile)
	in.NamespaceConfig.DeepCopyInto(&out.NamespaceConfig)
	out.AnnotationChurn = in.AnnotationChurn
	in.ResourceChurn.DeepCopyInto(&out.ResourceChurn)
	out.CleanupConfig = in.CleanupConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleLoadConfigSpec.
func (in *ScaleLoadConfigSpec) DeepCopy() *ScaleLoadConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ScaleLoadConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleLoadConfigStatus) DeepCopyInto(out *ScaleLoadConfigStatus) {
	*out = *in
	out.TotalResources = in.TotalResources
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Metrics = in.Metrics
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleLoadConfigStatus.
func (in *ScaleLoadConfigStatus) DeepCopy() *ScaleLoadConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ScaleLoadConfigStatus)
	in.DeepCopyInto(out)
	return out
}
